[package]
name = "massstab"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
color-eyre = "0.6.2"
ink_e2e = { git = "https://github.com/paritytech/ink", branch = "at/riscv", package = "ink_e2e" }
