[workspace]
exclude = [
    "contracts",
]

[package]
name = "massstab"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.44"
clap = { version = "4.4.8", features = ["derive"] }

contract-build = { package = "contract-build", git = "https://github.com/paritytech/cargo-contract", branch = "at/riscv" }
drink = { git = "https://github.com/ascjones/drink", package = "drink" }


# ink! contracts
crypto = { path = "./contracts/ink/crypto", features = ["ink-as-dependency"] }


